# fly.toml file generated for glider-inspection on 2022-05-14T11:04:37+03:00

app = "glider-inspection"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = ".fly/release.sh"

[env]
  DATABASE_URL = "file://data/sqlite.db"
  MIGRATE_ON_BOOT = "true"
  PORT = "8910"
  REDWOOD_DISABLE_TELEMETRY = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  destination = "/data"
  source = "data"

[[services]]
  http_checks = []
  internal_port = 8910
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
